### ISSUE TITLE
Development - Server

### ISSUE THREAD

**Issue by vinitha-vasanthkumar** [maidsafe/safenetwork.tech#114]
Update checklist (More specific to server code):

- [x] CORS handling based on production or development environment (refer https://github.com/shankar2105/email_subscription/issues/1)
- [x] No validation if the apiKey is not configured as expected. If the APIKey or the cred file is not present then the server should not even start.
- [x] Whitelist the netlify url on the server code for testing
- [x] Update Subscription API to get List ID as URL param (like http://hostname/api/subscribe/<listID>)

**Comment by vinitha-vasanthkumar** [comment]
- [ ] Design UI

- [ ] Validations - Confirmation & Error States

- [ ] Validations - Verify authenticity of email id using packages

- [ ] Consume Provided API Keys 

- [ ] Unit Test 

- [ ]

**Comment by shankar2105** [comment]
Following updates to be implemented on server:

- [ ] Whitelist the netlify url on the server code for testing
- [ ] Update Subscription API to get List ID as URL param (like http://hostname/api/subscribe/<listID>)

**Comment by S-Coyle** [comment]
LGTM
