### ISSUE TITLE
Unsubscribe manually then resubscribe edge case scenario

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safenetwork.tech#117]
Scenario we are looking to cover here is as follows:
- User subscribes to email subscription.
- User contacts MaidSafe and asks MaidSafe to manually remove them from the subscription list.
- A MaidSafe member of staff logs into Mailchimp and manually removes/unsubscribes them

**Comment by nadiaburborough** [comment]
Updated scenario:
Scenario we are looking to cover here is as follows:
- User unsubscribes to email subscription
- User is deleted from the database
- User unable to re-subscribe if they choose to in the future

**Comment by nadiaburborough** [comment]
@SarahPentland has a resolutio from mailchimp: On the 'Goodbye' email which the user receives after being deleted, there will be a link for the user to select if they choose to resubscribe again in the future. To be tested.

**Comment by S-Coyle** [comment]
Confirmed that clicking the "Subscribe" link the user gets in the "You are now unsubscribed" email allows them to re-subscribe
