### ISSUE TITLE
API Design List Id - to be retrieved or sent from client side instead of server?

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/safenetwork.tech#124]

**Comment by shankar2105** [comment]
@nadiaburborough we redesigned the API to handle the list id within the server by whitelisting the origin. So now based on the origin the server will pick the list id.

ref: https://github.com/maidsafe/safe-services/blob/master/email-subscription/node/src/config/app.ts#L1

cc @krishnaIndia

**Comment by S-Coyle** [comment]
Verified as working
