### ISSUE TITLE
Get Involved page - Underline on external CTA links (e.g. Developer Forum) needs to have a thickness in em

### ISSUE THREAD

**Issue by david-maidsafe** [maidsafe/safenetwork.tech#13]
- Underline on external CTA links (e.g. Developer Forum) needs to have a thickness in em, or otherwise relative to the font, in order to be proportional in size.

  - Also too much line-height

**Comment by david-maidsafe** [comment]
https://github.com/maidsafe/safenetwork_website/issues/161

**Comment by nadiaburborough** [comment]
Resolved

![Screen Shot 2019-06-24 at 10 45 43 AM](https://user-images.githubusercontent.com/35568923/60009143-3c5f7000-966d-11e9-9236-a2b7f95d557d.png)
