### ISSUE TITLE
Unable to resubscribe - using POST when we should be using PUT

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safenetwork.tech#132]
![image](https://user-images.githubusercontent.com/37112040/48200163-31fa9b00-e356-11e8-886f-a6cdf0dab580.png)

If I unsubscribe & attempt to resubscribe I get this error.

**Comment by safesurfer** [comment]
Issue got fixed. PR: https://github.com/maidsafe/safe-services/pull/6
