### ISSUE TITLE
Timeline Changes

### ISSUE THREAD

**Issue by SarahPentland** [maidsafe/safenetwork.tech#144]
Delete "PARSEC Dynamic membership whitepaper" and replace with "Java API for Mobile Development"

Replace PARSEC Code working  in a dynamic network with Integration of PARSEC in a dynamic permissionless network where nodes are free to join and leave

Delete Disjoint groups whitepaper replace with Introduction of Disjoint groups with secure message relay 

Replace parsec code working as the Network evolves in size with Enabling disjoint groups to merge and split whilst maintaining consensus 

Replace with Beta with Beyond

**Comment by S-Coyle** [comment]
@shankar2105 small typo - "permission less" should be 1 word - permissionless
![image](https://user-images.githubusercontent.com/37112040/49583214-61012e00-f94f-11e8-8e9d-44bd70445240.png)

**Comment by S-Coyle** [comment]
Verified that the above issue has now been fixed and that all other updates on this card have been made successfully
