### ISSUE TITLE
Replace Slack with Riot.im

### ISSUE THREAD

**Issue by david-maidsafe** [maidsafe/safenetwork.tech#145]
The SAFE Network Slack is now deprecated (due to the lack of features related to moderation and spam prevention). So it would now make sense to remove the Slack icons that are featured in the footer of https://safenetwork.tech/ and https://maidsafe.net/.

**Comment by david-maidsafe** [comment]
PR: https://github.com/maidsafe/safenetwork.tech/pull/112

**Comment by safesurfer** [comment]
QA verified
