### ISSUE TITLE
FAQ: What is Farming - replicated paragraph

### ISSUE THREAD

**Issue by david-maidsafe** [maidsafe/safenetwork.tech#154]
Hey @maidsafe can we fix and this https://safenetwork.tech/faq/#what-is-farming (there is twice the same paragraph): The process of providing resource and receiving Safecoin in return is called ‘Farming’. Each piece of encrypted network data is stored in a Farmer’s ‘Vault’, a data storage and management location on the Farmer’s computer which they cannot read, or access. The SAFE network is designed to self-manage these resources

**Comment by nadiaburborough** [comment]
QA verified. Resolved in #156

**Comment by calumcraig** [comment]
Removing from project as has been completed and closed.
