### ISSUE TITLE
Convert main navigation bar

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#164]
Convert the main navigation bar as a React component to adapt all the breakpoints of `v1.1` design. Use CSS Grid system to design its layout. Also integrate it with existing pages of the website..

**Comment by S-Coyle** [comment]
@shankar2105 not quite sure what to test this against - can you add a link to the design I should be comparing to? Thanks

**Comment by calumcraig** [comment]
Failed QA - https://github.com/maidsafe/safenetwork.tech/issues/191

Returned story to in progress.

**Comment by calumcraig** [comment]
Test results / notes can be found in this spreadsheet:

https://docs.google.com/spreadsheets/d/1nemlM-lmzGVVWXaT_8U4SY0940BiySBWeMR9uQSaUgc/edit#gid=0

Not that the Get involved issue has been resolved #191 this story is OK to pass QA - moving to done.
