### ISSUE TITLE
Convert global footer

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#165]
Convert the Global footer as a React component to adapt all the breakpoints of `v1.1` design. Use CSS Grid system to design its layout. Also integrate it with existing pages of the website.

**Comment by calumcraig** [comment]
Tested and no major (blocking) issues found.

Test results [here](https://docs.google.com/spreadsheets/d/1nemlM-lmzGVVWXaT_8U4SY0940BiySBWeMR9uQSaUgc/edit#gid=796942418).
