### ISSUE TITLE
Convert Press-kit page

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#167]
Convert the Press-kit page to adapt the specific breakpoints (i.e., XL, L, ML, S, XS, XXS) of v1.1 design. 
Use CSS Grid system to implement its layout. 
Also remove the existing/old and remap the router to point the new Press-kit page.

**Comment by calumcraig** [comment]
Tested and passed. Testing notes can be found [here](https://docs.google.com/spreadsheets/d/1nemlM-lmzGVVWXaT_8U4SY0940BiySBWeMR9uQSaUgc/edit#gid=0).
