### ISSUE TITLE
Convert FAQ page

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#168]
Convert the FAQ page to adapt the specific breakpoints (i.e., ML, S, XS, XXS) of v1.1 design.
Use CSS Grid system to implement its layout.
Also remove the existing/old and remap the router to point the new FAQ page.

**Comment by calumcraig** [comment]
Testing now complete on this change - a few minor issues were raised which have now been resolved. Moving this to QA Verified.

[Testing notes here.](https://docs.google.com/spreadsheets/d/1nemlM-lmzGVVWXaT_8U4SY0940BiySBWeMR9uQSaUgc/edit#gid=219066741)
