### ISSUE TITLE
https://safenetwork.tech/faq/#what-do-i-need-in-order-to-browse-the-safe-network

### ISSUE THREAD

**Issue by SarahPentland** [maidsafe/safenetwork.tech#173]
Change 2nd para to: 
You will need to create an account and download the SAFE Browser as the Network is still in Alpha 2.

**Comment by david-maidsafe** [comment]
changed as part of 
https://github.com/maidsafe/safenetwork.tech/issues/174

**Comment by david-maidsafe** [comment]
In PR: https://github.com/maidsafe/safenetwork.tech/pull/176

**Comment by calumcraig** [comment]
Removing from project as has been completed and closed.
