### ISSUE TITLE
https://safenetwork.tech/faq/#how-do-i-create-an-account

### ISSUE THREAD

**Issue by SarahPentland** [maidsafe/safenetwork.tech#174]
Delete: No account necessary.

To get started simply download the SAFE Browser and enter a SAFE site into the address bar. Some sample SAFE sites - Change to: To get started create an account, then download the SAFE Browser and enter...

**Comment by david-maidsafe** [comment]
okay, tweaked both daqs and getInv_faq to better represent the process (and match each other's answers).

**Comment by david-maidsafe** [comment]
In PR: https://github.com/maidsafe/safenetwork.tech/pull/176

**Comment by calumcraig** [comment]
Removing from project as has been completed and closed.
