### ISSUE TITLE
Get involved -Get the Safe Browser

### ISSUE THREAD

**Issue by SarahPentland** [maidsafe/safenetwork.tech#175]
Delete: just download and start browsing. 

Add: As the Network is still in Alpha testing you will need to register your IP in order to access the Network.

**Comment by david-maidsafe** [comment]
I've went with:
The SAFE Browser is the Network’s dedicated web browser. To access the network while it is in Alpha you'll need to have a forum account with <a href="https://safenetforum.org/t/trust-level-1-basic-user-requirements/15200">basic trust level</a> and get an <a href="https://invite.maidsafe.net">invite token</a>.  Then just download and start browsing.

**Comment by david-maidsafe** [comment]
In PR: https://github.com/maidsafe/safenetwork.tech/pull/176

**Comment by calumcraig** [comment]
Removing from project as has been completed and closed.
