### ISSUE TITLE
Link to Parsec White Paper is dead

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#185]
**Steps to reproduce:**
1. Launch Netifly mock up for Press Kit page v1.1 #178
https://deploy-preview-178--keen-stonebraker-bb1a10.netlify.com/press-kit/
2. Click on "Download" button for Parsec Whitepaper.

**Expected result:**
Button click will trigger download of Parsec Whitepaper.
**Actual result:**
Button click does nothing. On inspection of the code we can see there is no URL or file location specified:
https://github.com/maidsafe/safenetwork.tech/pull/178/files#diff-0aef54cfb8479c45b9c64b147dc1858cR11

**Comment by shankar2105** [comment]
Closing this as this issue got fixed in this PR #205

**Comment by calumcraig** [comment]
Tested on latest commit on Dev branch.

Link now functions correctly, the Parsec White Paper PDF opens in a new browser tab:

![image](https://user-images.githubusercontent.com/44327924/57384139-eeb7a280-71a7-11e9-8b57-f03e69846be9.png)

**Comment by calumcraig** [comment]
QA verified - moving to done.
