### ISSUE TITLE
"Sign up" button misaligned

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#187]
**Steps to reproduce:**
1. Launch Netifly mock up for Press Kit page v1.1 #178
https://deploy-preview-178--keen-stonebraker-bb1a10.netlify.com/press-kit/
2. Resize browser width to less than 1455 pixels.

**Expected result:**
On screen elements are correctly aligned.
**Actual result:**
"Sign up" button is hard against the email address textbox in the footer area:
Launch Netifly mock up for Press Kit page v1.1 #178
https://deploy-preview-178--keen-stonebraker-bb1a10.netlify.com/press-kit/
![image](https://user-images.githubusercontent.com/44327924/53947696-2e85df00-40be-11e9-9d52-106f8c1a2a62.png)
![image](https://user-images.githubusercontent.com/44327924/53947682-262da400-40be-11e9-8a9d-f385ab289509.png)

**Comment by shankar2105** [comment]
Close this issue as this got fixed in this PR https://github.com/maidsafe/safenetwork.tech/pull/205

**Comment by calumcraig** [comment]
QA verified.

Can confirm that this issue has been resolved. Current behaviour:

![image](https://user-images.githubusercontent.com/44327924/57370222-85c03280-7187-11e9-94b9-48ff974d3541.png)
