### ISSUE TITLE
For FAQ: 'What is stopping a hosting provider from farming?' in the repsonse, the 1 and 0 looks like an i and o

### ISSUE THREAD

**Issue by david-maidsafe** [maidsafe/safenetwork.tech#19]
Screenshot of issue:-
![](https://user-images.githubusercontent.com/37243695/42637242-86c09b3e-85e2-11e8-9923-b82598bcbda7.png)

**Comment by david-maidsafe** [comment]
https://github.com/maidsafe/safenetwork_website/issues/150

**Comment by david-maidsafe** [comment]
We can solve this if we choose to use Proportional Lining for the numerals for the font.
 @JimCollinson commented 11 days ago:

I've added this in the css with font-feature-settings: "lnum"; font-variant-numeric: lining-nums; but it looks like the font we've included from webpack does not inlcude these glyphs.

Can we add the proper/full font? @shankar2105

**Comment by nadiaburborough** [comment]
![Screen Shot 2019-06-24 at 10 43 38 AM](https://user-images.githubusercontent.com/35568923/60009012-fb675b80-966c-11e9-826f-84b5b8f38724.png)
Resolved
