### ISSUE TITLE
Hyperlinks not indicated

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#193]
**Steps to reproduce:**
1. Navigate to Get Involved page:
https://deploy-preview-170--keen-stonebraker-bb1a10.netlify.com/get-involved/
2. Inspect "Get the SAFE Browser" paragraph.

**Expected result:**
Any hyperlinked text will be formatted as such, eg:
![image](https://user-images.githubusercontent.com/44327924/53967988-25146b00-40ee-11e9-880e-6f64e0e79dba.png)
**Actual result:**
There are two hyperlinks in this paragraph that are not indicated - just formatted as normal text, although they are clickable and do function:
"basic trust level"
"invite token":
![image](https://user-images.githubusercontent.com/44327924/53968284-a3710d00-40ee-11e9-8b1e-1fb8e386363c.png)

**Comment by shankar2105** [comment]
Closing this issue as this is related to website v1.0 and website v1.1 has a different UI for it.

**Comment by calumcraig** [comment]
This is no longer a relevant issue as noted above. Moving to done.
