### ISSUE TITLE
Footer - social icons not in correct order for small browser

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#204]
**Steps to reproduce:**
1. Launch Netlify preview of PR https://deploy-preview-202--keen-stonebraker-bb1a10.netlify.com/
2. Resize browser window to small size: <1300
![image](https://user-images.githubusercontent.com/44327924/55176392-f6cbfd80-5178-11e9-9699-0656f71d108d.png)
3. Scroll to footer

**Expected:** (from Figma mock up)
![image](https://user-images.githubusercontent.com/44327924/55176451-0ea38180-5179-11e9-84a3-1a4661979c1c.png)
**Actual:**
![image](https://user-images.githubusercontent.com/44327924/55176504-27ac3280-5179-11e9-8ef6-42aa382f4aac.png)
(Second row of icons is in different order to mock up.)

**Comment by JimCollinson** [comment]
I don't think this is problem, will close.
