### ISSUE TITLE
Get Involved page v1.1 - Convert base layout for default view

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#206]
Implement base layout of `Get Involved` page v1.1 for default view (Excluding invite process component)

>`Story points: 3`

**Comment by calumcraig** [comment]
Tested against Netlify preview https://deploy-preview-236--keen-stonebraker-bb1a10.netlify.com/get-involved/#claimInvite

Layout looks good, there was [one minor issue](https://github.com/maidsafe/safenetwork.tech/issues/252) found during testing which has now been resolved. Test results can be found [here](https://docs.google.com/spreadsheets/d/1nemlM-lmzGVVWXaT_8U4SY0940BiySBWeMR9uQSaUgc/edit#gid=1664720646).

Closing this issue and moving to done.
