### ISSUE TITLE
Get Involved page v1.1 - Convert invite component for default view

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#207]
Implement invite component layout of `Get Involved` page v1.1 for default view
Integrate it with `Get Involved` page base layout

>`Story points: 3`

**Comment by calumcraig** [comment]
Tested against Netlify preview https://deploy-preview-236--keen-stonebraker-bb1a10.netlify.com/get-involved/#claimInvite

Invite component looking good, only one minor issue discovered during testing: https://github.com/maidsafe/safenetwork.tech/issues/261 which needs URL hacking to manifest itself.

Testing results can be found [here](https://docs.google.com/spreadsheets/d/1nemlM-lmzGVVWXaT_8U4SY0940BiySBWeMR9uQSaUgc/edit#gid=1664720646).

Closing this issue and moving to done.
