### ISSUE TITLE
Convert Get Involved page v1.1 responsiveness

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#208]
Implement `Get Involved` page v1.1 responsiveness to fit all it's breakpoints (XL, L, M, S, XS, XXS and XXXS)

>`Story points: 4`

**Comment by calumcraig** [comment]
Tested against Netlify preview: https://deploy-preview-236--keen-stonebraker-bb1a10.netlify.com/get-involved/#claimInvite

Responsiveness of page looking good - tested on Chrome and Firefox - [results here](https://docs.google.com/spreadsheets/d/1nemlM-lmzGVVWXaT_8U4SY0940BiySBWeMR9uQSaUgc/edit#gid=1664720646). (Might need to check tab of the spreadsheet.)
Closing this issue and moving to done.
