### ISSUE TITLE
Roadmap page v1.1 - Convert base layout for default view

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#209]
Implement base layout of `Roadmap` page v1.1 for default view (Exclude accordion and timeline components)

>`Story points: 4`

**Comment by calumcraig** [comment]
Tested the layout of the roadmap page extensively during testing of issue #212  - please see that for results.

Other than bugs raised during that testing, page is working as expected. Closing this issue and moving to done.
