### ISSUE TITLE
Roadmap page v1.1 - Convert timeline component for default view

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#211]
Implement timeline component layout of `Roadmap` page v1.1 for default view
Integrate it with Roadmap page base layout

>`Story points: 3`

**Comment by calumcraig** [comment]
Tested the layout of the roadmap page extensively during testing of issue #212 - please see that for results.

Other than bugs raised during that testing, page is working as expected. Closing this issue and moving to done.

**Comment by calumcraig** [comment]
Closed this issue in error - reopening for the time being.

**Comment by calumcraig** [comment]
Bugs found for this component - #288  #289 #291

**Comment by calumcraig** [comment]
Found during testing this - #308

**Comment by calumcraig** [comment]
QA verified - other than the issues referenced above this component is working as expected.

Closing this issue and moving to done.
