### ISSUE TITLE
FAQs - text aligned all the way to left of screen IE11

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#227]
Open FAQs page in IE11 https://deploy-preview-224--keen-stonebraker-bb1a10.netlify.com/faq/

**Expected:**
Text aligned correctly on screen
**Actual:**
Text aligned all the way left of page:
![image](https://user-images.githubusercontent.com/44327924/55944996-c341a680-5c41-11e9-8570-2ef5f5151a78.png)

**Comment by calumcraig** [comment]
NB, this is only seen for browser widths greater than 1000 pixels - at smaller sizes than this the page displays correctly.

**Comment by shankar2105** [comment]
@calumcraig this version of the website don't support for IE
We've previous issues regarding IE -> #79

**Comment by S-Coyle** [comment]
Just to clarify our position on IE11 - we do try to support it where possible, and investigate issues that arise. With the technology we are using on this website we know it is not fully compatible with IE11 and are accepting that there will be minor issues such as display, formatting, etc. As long as it is readable and usable then we are accepting that for now.

**Comment by calumcraig** [comment]
As noted above, IE support is not a priority and this behaviour is accepted. Closing issue as will not fixed.
