### ISSUE TITLE
Home page v1.1 - Convert base layout for default view

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#240]
Implement base layout of `Home page` v1.1 for default view 

> Story point: 8

**Comment by calumcraig** [comment]
Testing on [latest Netlify preview](https://deploy-preview-356--keen-stonebraker-bb1a10.netlify.com/) which fixes some issues found in initial testing.

QA verified. [Test results here](https://docs.google.com/spreadsheets/d/1nemlM-lmzGVVWXaT_8U4SY0940BiySBWeMR9uQSaUgc/edit?pli=1#gid=1881709118).

Moving to done.
