### ISSUE TITLE
Home page v1.1 - Implement responsiveness for large screens

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#242]
Implement `Home page` v1.1 to fit all large screen breakpoints (M, L and XL)

> Story point: 4

**Comment by calumcraig** [comment]
Testing on [latest Netlify preview](https://deploy-preview-356--keen-stonebraker-bb1a10.netlify.com/) which fixes some issues found in initial testing.

QA verified. [Test results here](https://docs.google.com/spreadsheets/d/1nemlM-lmzGVVWXaT_8U4SY0940BiySBWeMR9uQSaUgc/edit?pli=1#gid=1881709118).

Moving to done.
