### ISSUE TITLE
SafeCoin page v1.1 - Convert base layout for default view

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#243]
Implement base layout of `SafeCoin` page v1.1 for default view 

> Story point: 4

**Comment by calumcraig** [comment]
QA verified - [results here](https://docs.google.com/spreadsheets/d/1nemlM-lmzGVVWXaT_8U4SY0940BiySBWeMR9uQSaUgc/edit#gid=1619534350).

Moving to done.
