### ISSUE TITLE
SafeCoin page v1.1 responsiveness

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#244]
Implement `SafeCoin` page v1.1 to fit all it's breakpoints (L, M, S, XS, XXS and XXXS)

> Story point: 4

**Comment by calumcraig** [comment]
QA verified - [results here](https://docs.google.com/spreadsheets/d/1nemlM-lmzGVVWXaT_8U4SY0940BiySBWeMR9uQSaUgc/edit#gid=1619534350)

Moving to done.
