### ISSUE TITLE
How it works page v1.1 responsiveness

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#246]
Implement `How it works` page v1.1 to fit all it's breakpoints (L, M, S, XS, XXS and XXXS)

> Story point: 4

**Comment by calumcraig** [comment]
Tested on `dev` branch. [Results here](https://docs.google.com/spreadsheets/d/1nemlM-lmzGVVWXaT_8U4SY0940BiySBWeMR9uQSaUgc/edit?pli=1#gid=1720597086).

There are a few issues which have not yet been fully resolved but none are blockers.

QA verified - moving to done.
