### ISSUE TITLE
Term & Condition page v1.1 - Convert the layout with responsiveness

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#247]
Implement the `Term & Condition` page v1.1 for default view and also to fit all it's breakpoints (L, S, XS, XXS and XXXS)

> Story point: 6

**Comment by calumcraig** [comment]
Currently testing this - [results here](https://docs.google.com/spreadsheets/d/1nemlM-lmzGVVWXaT_8U4SY0940BiySBWeMR9uQSaUgc/edit?pli=1#gid=1236075576).

There are a couple of issues which need to be resolved (one has been fixed but the PR not yet merged) before this can pass QA.

**Comment by calumcraig** [comment]
The responsiveness of the page was previously tested with the now outdated content and was OK apart from one relevant issue - the banner displaying full width.

This has now been resolved and the content and title updated. Working fine at all breakpoints.

![image](https://user-images.githubusercontent.com/44327924/57864403-b9d4cc80-77f3-11e9-878a-1d75c4c3796d.png)

QA verified - moving to done.
