### ISSUE TITLE
Fundamentals page v1.1 - Convert the layout with responsiveness

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#267]
Implement the Fundamentals page v1.1 for default view and also to fit all it's breakpoints (L, S, XS, XXS and XXXS)

> Story point: 6

**Comment by calumcraig** [comment]
QA verified.

Tested the various breakpoints on a range of browsers. [Test results here](https://docs.google.com/spreadsheets/d/1nemlM-lmzGVVWXaT_8U4SY0940BiySBWeMR9uQSaUgc/edit#gid=1171611826).

Moving to done.
