### ISSUE TITLE
At `xxxs` the table key should probably have padding 16px l/r so it doesn't get text collisions.

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#270]
At `xxxs` the table key should probably have padding 16px l/r so it doesn't get text collisions.

Also, might been to truncate `Development` to `Code` and `Complete` to `Done` to save space at that size.

_Originally posted by @JimCollinson in https://github.com/maidsafe/safenetwork.tech/pull/266#issuecomment-489094592_

**Comment by shankar2105** [comment]
Closing this issue as this is duplicate of #329.

**Comment by safesurfer** [comment]
Since it is similar to #329 and referenced to it, moving it to done.
