### ISSUE TITLE
Roadmap Page: Something strange going on at mobile sizes with the right hand side at XXXS

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#272]
Something strange going on at mobile sizes with the right hand side. like the whole body isn't spanning the full width.

<img width="329" alt="Screenshot 2019-05-03 14 19 58" src="https://user-images.githubusercontent.com/13061030/57140046-bdf1fa80-6dae-11e9-8fdc-642bed0345cf.png">

_Originally posted by @JimCollinson in https://github.com/maidsafe/safenetwork.tech/pull/266#issuecomment-489093121_

**Comment by calumcraig** [comment]
There is an issue with small sizes of the browser on this page - #305 

Moving this back to in development for the time being.

**Comment by calumcraig** [comment]
Testing on `dev` branch: `b186625 (HEAD -> dev, origin/dev) chore/conflicts: fix merge conflicts`

Looks good now at XXXS (<500 pixels wide):

![image](https://user-images.githubusercontent.com/44327924/57921321-fc9ab100-7894-11e9-8372-e2488fca2149.png)

![image](https://user-images.githubusercontent.com/44327924/57921330-03292880-7895-11e9-9d01-1ed67bf5c6d5.png)

**Comment by calumcraig** [comment]
QA verified - closing and moving to done.
