### ISSUE TITLE
Roadmap - accordion sections reopen when navigate away from page and back again.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#273]
Testing Roadmap PR #266 Netlify preview: https://deploy-preview-266--keen-stonebraker-bb1a10.netlify.com/roadmap/

**Steps to reproduce:**
1. Click to open some accordion sections:
![image](https://user-images.githubusercontent.com/44327924/57145145-796c5c00-6dba-11e9-9c7d-2ff5dd08bf55.png)
2. Click again to close them: 
![image](https://user-images.githubusercontent.com/44327924/57145201-9e60cf00-6dba-11e9-8586-a02f5dc94b34.png)
3. Click on a link to move to a different page, eg FAQs:
![image](https://user-images.githubusercontent.com/44327924/57145271-cc461380-6dba-11e9-975b-3a727b2cbfd7.png)
4. Click on browser back to return to the roadmap page.

**Expected (TBC):**
Accordion sections to be closed as had left them.
**Actual:**
Accordion sections are open:
![image](https://user-images.githubusercontent.com/44327924/57145360-fac3ee80-6dba-11e9-9842-b891e6307ca2.png)

**Comment by calumcraig** [comment]
This is related to the page URL - when clicking an accordion section there is tag appended to the URL, eg `#lorem-ipsum-dolor-sit`. When the user navigates away from and back to the page the browser returns to the last URL.

I think we probably want to wait until there is genuine content and see how it behaves then and make a call whether this is an actual bug or not.

**Comment by shankar2105** [comment]
Closing the accordion should remove the hash from the url, which got fix in PR #299

**Comment by calumcraig** [comment]
QA verified.

Tested this against Netlify preview for PR #299 https://deploy-preview-299--keen-stonebraker-bb1a10.netlify.com/roadmap/#

Clicking on the accordion sections to close them now removes the appended `#` from the URL and thus prevents this behaviour occurring. Following the steps to reproduce detailed above does indeed now result in the expected results.

Closing this issue and moving to done.
