### ISSUE TITLE
Fix global footer newsfeed title style 

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#278]
Below XS breakpoint, remove `mouse over` and `pressed` state style of global footer newsfeed title.

**Comment by calumcraig** [comment]
Tested on latest commit on dev branch `dca523c (HEAD -> dev, origin/dev) Fixes: Roadmap accordion styling and handled close event to remove hash from url (#299)`

There is no longer any hover state for the Newsletter title in the global footer - previously the line underneath the text had turned yellow upon hover. The title is not clickable so the pressed state is N/A.

**Comment by calumcraig** [comment]
QA verified - moving to done.
