### ISSUE TITLE
Update PressKit page medias link and state styling

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#279]
Update PressKit page medias link and state styling as per Figma design

**Comment by calumcraig** [comment]
Tested against latest commit on Dev branch.

All links / buttons OK except the Creative Commons link - issue #315 

Test results:


Page component | Enabled | Hover | Pressed | Active | Active hover
-- | -- | -- | -- | -- | --
How it works | OK | OK | OK | OK | OK
Safecoin | OK | OK | OK | OK | OK
Roadmap | OK | OK | OK | OK | OK
Fundamentals | OK | OK | OK | OK | OK
FAQs | OK | OK | OK | OK | OK
Press Kit | OK | OK | OK | OK | OK
Get Involved | OK | OK | OK | OK | OK
Hamburger | OK | OK | OK |   |  
Copy text snippet 1 | OK | OK | OK |   |  
Copy text snippet 2 | Not functioning | Not functioning | Not functioning |   |  
Copy text snippet 3 | Not functioning | Not functioning | Not functioning |   |  
Request interview | OK | OK | OK |   |  
Guardian | OK | OK | OK |   |  
Tech Crunch | OK | OK | OK |   |  
Spectrum | OK | OK | OK |   |  
Logos 1 | OK | OK | OK |   |  
Logos 2 | OK | OK | OK |   |  
Logos 3 | OK | OK | OK |   |  
Logos 4 | OK | OK | OK |   |  
Creative Commons | Fail | Fail | Fail | https://github.com/maidsafe/safenetwork.tech/issues/315 |  
Image pack | OK | OK | OK |   |  
PARSEC WP | OK | OK | OK |   |  
Network Primer | OK | OK | OK |   |

**Comment by calumcraig** [comment]
Moving this issue to done.
