### ISSUE TITLE
Update roadmap page accordion state styling

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#280]
Update roadmap page accordion state styling as per Figma design

**Comment by calumcraig** [comment]
Tested against latest commit on `Dev` branch - dca523c (HEAD -> dev, origin/dev) Fixes: Roadmap accordion styling and handled close event to remove hash from url (#299).

Styling of roadmap accordion sections now working as specified in the Figma design preview.

![RoadmapAccordionStyling](https://user-images.githubusercontent.com/44327924/57446238-2d069d80-724c-11e9-9d40-0a44aec4fb3a.gif)

**Comment by calumcraig** [comment]
QA verified - moving to done.
