### ISSUE TITLE
Incorrect icon for `Design` - should be layout icon

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safenetwork.tech#287]
![image](https://user-images.githubusercontent.com/37112040/57231483-808da700-7012-11e9-8227-2c37b4c9e423.png)

Confirmed with Jim that this should be the layout icon, not a bulb

**Comment by safesurfer** [comment]
QA verified, seeing Layout icon for `Design`. 

![image](https://user-images.githubusercontent.com/27578024/57683662-c91c1480-7651-11e9-8a6d-0a315090d308.png)
