### ISSUE TITLE
`Upcoming Milestones` section heading text positioned too far left in screen sizes XS, XXS and XXXS

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safenetwork.tech#291]
![image](https://user-images.githubusercontent.com/37112040/57235387-ab7bf900-701a-11e9-86db-f0df56936bfa.png)

Should be positioned to start in line with the `Lorem ipsum dolor` text, according to designs

**Comment by safesurfer** [comment]
QA verified, in XS `Upcoming...` aligned with the text `Lorem..`, in XXS and XXXS, `Upcoming milestone` is away from left by 56 px and 30 px respectively, where in figma, it is 30px for both sizes, which is wrong according to @shankar2105 . So, moving it to Done.
