### ISSUE TITLE
Display issues on XXXS screen size

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safenetwork.tech#292]
I'm seeing several display issues with screen sizes of between 300-400. I'm sure we previously set the minimum screen size to test as 300 so will log these. Will add these under 1 issue for now - can be split out if required.
1. Overlapping text.
2. Margin appears on right side of screen.
3. Status key image looks awful
![image](https://user-images.githubusercontent.com/37112040/57237822-efbdc800-701f-11e9-8692-c65b5804aa94.png)
4. Status images appearing outside of table - maybe why the margin is appearing?
5. Button text appearing outside button
![image](https://user-images.githubusercontent.com/37112040/57237910-154ad180-7020-11e9-8441-86db5bd5815e.png)

Replicated on Chrome, Safari & FF

**Comment by calumcraig** [comment]
Tested on Netlify preview: https://deploy-preview-394--keen-stonebraker-bb1a10.netlify.com/get-involved/

XXXS browser is now looking as expected with regards to the issues referenced above.
![image](https://user-images.githubusercontent.com/44327924/57862087-b2abbf80-77ef-11e9-9ad9-a1cabca04bb9.png)
![image](https://user-images.githubusercontent.com/44327924/57862144-c9eaad00-77ef-11e9-84c7-6ddc949a776d.png)

All other issues (not in screenshots) have also been resolved.

QA verified - closing and moving to done.
