### ISSUE TITLE
Roadmap - horizontal scroll bar appears at 614 pixels screen width - Firefox, 410 pixels - Chrome

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#301]
Testing against PR #299 and latest commit on dev branch (both have same issue). When resize browser to 614 pixels or below a horizontal scroll bar appears.
Firefox:
![image](https://user-images.githubusercontent.com/44327924/57299240-f86bd800-70cb-11e9-9ed1-6f15266bbf2f.png)
![image](https://user-images.githubusercontent.com/44327924/57299247-fefa4f80-70cb-11e9-807a-dd220d5592db.png)

**Comment by calumcraig** [comment]
This is found in Fifefox - the steps above in Chrome **don't** result in the scroll bar being displayed.

**Comment by calumcraig** [comment]
In Chrome:
![image](https://user-images.githubusercontent.com/44327924/57301133-2c48fc80-70d0-11e9-930f-c7c3bde7c061.png)
![image](https://user-images.githubusercontent.com/44327924/57301150-35d26480-70d0-11e9-9154-fe5fb5425403.png)

**Comment by S-Coyle** [comment]
@shankar2105 Should probably also mention, as it will affect the priority here, that in Firefox this results in the right side of the expandable widget being pushed out of the screen at around 570px wide and below. User would have to scroll right to see the `Status` icon and to read the text.
![image](https://user-images.githubusercontent.com/37112040/57302385-f78a7480-70d2-11e9-9e7a-69f1dbacc120.png)

Widget resizes fine in Chrome & Safari

**Comment by calumcraig** [comment]
And, on Edge, it's 411 pixels:
![image](https://user-images.githubusercontent.com/44327924/57302578-72538f80-70d3-11e9-95ff-07c193e896c6.png)
![image](https://user-images.githubusercontent.com/44327924/57302622-88615000-70d3-11e9-8a4f-c92cc94e0f0d.png)

**Comment by safesurfer** [comment]
QA verified, horizontal scroll bar no longer appears at 410 px in Chrome and 610 px in firefox
![image](https://user-images.githubusercontent.com/27578024/57681291-05994180-764d-11e9-914b-e406fac51f86.png)
