### ISSUE TITLE
Roadmap - no LH margin for accordion sections at XS browser size.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#305]
In XS browser size, 768 - 1000 pixels wide there should be a margin to the left of the accordion sections, as seem in the Figma design mock up:

![image](https://user-images.githubusercontent.com/44327924/57313688-03346600-70e8-11e9-8b56-59631eea75dc.png)

However there is not on the Netlify preview:

![image](https://user-images.githubusercontent.com/44327924/57313644-ef88ff80-70e7-11e9-975c-098744312629.png)

**Comment by safesurfer** [comment]
LH margin issue has been fixed, but seeing the following issue. On Roadmap page, the accordions are not as in figma, they are all overlapping with the icons from small size, <= 1300. (latest dev branch)

![image](https://user-images.githubusercontent.com/27578024/57623709-f4e5be80-75ad-11e9-814a-4fa1b45ac4d4.png)

**Comment by S-Coyle** [comment]
checked the original issue, as well as Srini's follow up bug, in Chrome, FF and Safari - all seems fine now
