### ISSUE TITLE
Press Kit layout broken

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#307]
Seems like some of the global style changes may have broken the Press Kit layout at various sizes.

**Comment by JimCollinson** [comment]
A few suggested fixes:

Some recommended fixes:

```.pressKitTexts .intro .textSnippet:after {
    min-height: 36px;
}
```
```.pressKitTexts .aboutSafecoin .textSnippet:after, .pressKitTexts .projectAim .textSnippet:after {
    min-height: 36px;
}
```

**Comment by JimCollinson** [comment]
`projectAim` inner container is missing right padding

**Comment by JimCollinson** [comment]
Also, incorrect top padding on the `pressFreedom` and `revenueStream` divs.

Layout all out of whack, at the larger VP sizes.

**Comment by JimCollinson** [comment]
Mostly fixed in PR #297

**Comment by S-Coyle** [comment]
Already approved by design as part of PR review - QA not required here
