### ISSUE TITLE
Roadmap - Timeline - text out of alignment at S and XS browser sizes

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#308]
Tested on latest commit on dev branch.

At Small and XSmall browser sizes (1300 - 768 pixels wide) we can see text out of alignment with icons:

**Expected:**
![image](https://user-images.githubusercontent.com/44327924/57368750-d170dd00-7183-11e9-95e0-8065e99aed79.png)
**Actual:**
![image](https://user-images.githubusercontent.com/44327924/57368774-e483ad00-7183-11e9-9f1f-eaface59c216.png)

**Comment by safesurfer** [comment]
Tested on Small and XSmall sizes, now the text is aligned with the top of the icons.
