### ISSUE TITLE
Press Kit - Creative Commons link wrong styling

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#315]
Press Kit - Creative Commons link is currently styled as `Underline link / minor`:

![image](https://user-images.githubusercontent.com/44327924/57438011-e2305a00-723a-11e9-8119-0b6d4f63ffd5.png)

Should be custom styling - TBC.

**Comment by shankar2105** [comment]
Closing this issue as it got fix in latest code

**Comment by safesurfer** [comment]
QA verified
