### ISSUE TITLE
Proper float for Asides on HIW page

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#316]
The floating/wrapping of text doesn't really work terribly well when it's faked with right padding like it currently is.

Doesn't work well at all around the `when will it be finished` box. Produces a large space above, and text running too close to the box at the left.

![image](https://user-images.githubusercontent.com/13061030/57290233-e6cb0600-70b4-11e9-8c02-3556dfd2ada2.png)

Can we use a genuine float technique?

Also note that the `When Will it be finished box` can/should be a fixed width to allow this; not alligned to thew grid... it can be in the same container as the paragraphs.

_Originally posted by @JimCollinson in https://github.com/maidsafe/safenetwork.tech/pull/294#issuecomment-490011422_

**Comment by calumcraig** [comment]
Testing latest commit on `dev` branch: `446dd97 (HEAD -> dev, origin/dev) Thin background videos (#345)`

The yellow aside text box can be seen to push into the body of the text as the browser is made narrower:
![image](https://user-images.githubusercontent.com/44327924/57706393-8f510b00-765d-11e9-8ea3-4611c85137fb.png)
![image](https://user-images.githubusercontent.com/44327924/57706410-9841dc80-765d-11e9-9648-2828fc4c08a8.png)
![image](https://user-images.githubusercontent.com/44327924/57706429-a263db00-765d-11e9-8083-b8a536360856.png)
Until it becomes a box in the middle of the page:
![image](https://user-images.githubusercontent.com/44327924/57706474-b8719b80-765d-11e9-9335-542ace13841a.png)
The upper aside (picture of a laptop) behaves in a similar manner.

QA verified, moving to done.
