### ISSUE TITLE
Full width Video at top of HIW page

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#317]
As discussed with @shankar2105 HIW page should be changed to have the BG video full width.

Also required is:

- Light coloured main nav (with red active highlight
- Alignment of no-page nave box as per amended Figma file

**Comment by S-Coyle** [comment]
On XL screens (and I assume anything > XL) the video is not full width. See screenshot below:
![image](https://user-images.githubusercontent.com/37112040/57846549-626f3600-77cc-11e9-9bbb-1fe7c235dd85.png)

Passing back to In Development

**Comment by calumcraig** [comment]
Tested on Netlify preview: https://deploy-preview-393--keen-stonebraker-bb1a10.netlify.com/how-it-works/

Video now spans the full width of the screen:

![image](https://user-images.githubusercontent.com/44327924/57863590-45e5f480-77f2-11e9-9982-04d8f1c91bb3.png)

**Comment by calumcraig** [comment]
QA verified - moving to done.
