### ISSUE TITLE
Add `mailto:` invite link in Get Involved page to start and email client. *Needs Email Content*

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#320]

**Comment by david-maidsafe** [comment]
@JimCollinson / @shankar2105 

https://docs.google.com/document/d/1zXMkmg_3rLcGn1ikep01p3gNGMXxvt6ncdC4aUuv9p0/edit?usp=sharing

**Comment by calumcraig** [comment]
Testing on `dev`: `be67afb (HEAD -> dev, origin/dev) Merge pull request #386 from shankar2105/invite_process_fix`

Clicking on the `Request invite` button from the `Get Invite` modal 
![image](https://user-images.githubusercontent.com/44327924/57865814-2d77d900-77f6-11e9-81c5-dd473c1c432d.png)

launches the default email client with a prepopulated email:
![image](https://user-images.githubusercontent.com/44327924/57865643-df62d580-77f5-11e9-9cca-c101d65221a7.png)

**Comment by calumcraig** [comment]
QA verified - closing and moving to done.
