### ISSUE TITLE
Add "why do I need an Invite" FAQ to get involved page; and link to it from invite modal

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#321]
cc'ing you on here @david-maidsafe so you can oversee the content side of things

**Comment by david-maidsafe** [comment]
@JimCollinson / @shankar2105:

https://docs.google.com/document/d/1ZTr9PERZeRjcSgXhTHCNjuaNXRA1pQ9fDApxa3ghHgQ/edit?ts=5cdab349

**Comment by calumcraig** [comment]
Testing on `dev` branch: `be67afb (HEAD -> dev, origin/dev) Merge pull request #386 from shankar2105/invite_process_fix`

Link from invite modal now takes user down to the relevant FAQ section on the same page:
![image](https://user-images.githubusercontent.com/44327924/57865394-6bc0c880-77f5-11e9-8cfb-7221b66307fe.png)

QA verified - closing and moving to done.
