### ISSUE TITLE
Fundamentals: At `XXXS` text in expanded accordion content (`Accordion__container`) should have l/r padding of `30px`

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#324]
at `XXXS` text in expanded accordion content (`Accordion__container`) should have l/r padding of `30px`

_Originally posted by @JimCollinson in https://github.com/maidsafe/safenetwork.tech/pull/284#issuecomment-490872436_

**Comment by S-Coyle** [comment]
Already reviewed by design - no QA required
