### ISSUE TITLE
Safecoin - Get Involved button wrong colour of text

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#325]
Testing on latest commit on `Dev` branch: `8acef10 (HEAD -> dev, origin/dev) Invite process broken links (#309)`

Expected:
![image](https://user-images.githubusercontent.com/44327924/57454585-1880d000-7261-11e9-9627-5a0b643d1cdb.png)
Actual:
![image](https://user-images.githubusercontent.com/44327924/57454618-29314600-7261-11e9-9360-a42ec3039a8f.png)

**Comment by shankar2105** [comment]
Closing this as issue got fixed in latest code.

**Comment by calumcraig** [comment]
Testing on latest `dev` branch commit: `4a41b54 (HEAD -> dev, origin/dev) Safecoin page minor styling issues (#344)`

Can see this issue has been fixed:

![image](https://user-images.githubusercontent.com/44327924/57627364-ca850880-758f-11e9-9abb-0629a1e67865.png)

QA Verified - moving to done.
