### ISSUE TITLE
Safecoin - link to OpenLedger not pointing at MaidSafe coin.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#331]
Testing on `Dev` branch: `8acef10 (HEAD -> dev, origin/dev) Invite process broken links (#309)`

In FAQs section there are links to various cryptocurrency exchanges:
![image](https://user-images.githubusercontent.com/44327924/57457961-72d15f00-7268-11e9-85cb-bcfcf793a3e3.png)

**Expected:**
OpenLedger link points to `https://openledger.io/market/MAID_BTC`
**Actual:**
OpenLedger link points to `https://openledger.io/welcome`

**Comment by david-maidsafe** [comment]
got a fix ready - just need the dev branch to pull from master and I can raise a PR (I think).

**Comment by calumcraig** [comment]
Fixed by #446

**Comment by calumcraig** [comment]
Verified there are no longer any links to the Open Ledge exchange on the latest version of the site so no longer an issue.

Moving to done.
