### ISSUE TITLE
Safecoin - Close Group Consensus link takes to page misaligned

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#335]
Testing on `dev` branch: `0363180 (HEAD -> dev, origin/dev) Resolve roadmap style issues (#313)`

1. Safecoin page
2. Click on Close Group Consensus link
![image](https://user-images.githubusercontent.com/44327924/57513996-67814080-7307-11e9-8513-62075e0b7146.png)

**Expected:**
Target page is properly lined up with the relevant section.
**Actual:**
"What is Close Group Consensus?" section is not lined up properly:
![image](https://user-images.githubusercontent.com/44327924/57513943-4ae50880-7307-11e9-95bc-8ee303830b60.png)

**Comment by shankar2105** [comment]
Closing this as this issue no longer exist

**Comment by safesurfer** [comment]
QA verified, moving it to Done.
