### ISSUE TITLE
Safecoin - back on browser returns to top of the page

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#336]
Testing on dev branch: 0363180 (HEAD -> dev, origin/dev) Resolve roadmap style issues (#313)

1. Safecoin page
2. Click on "Close Group Consensus" link to be taken to the FAQs page.
![image](https://user-images.githubusercontent.com/44327924/57514221-db234d80-7307-11e9-8848-11b6671ebdc6.png)
3. Click back on browser.

**Expected:**
User is returned to the same part of the Safecoin page they left.
**Actual:**
User is returned to the top of the Safecoin page:
![image](https://user-images.githubusercontent.com/44327924/57514235-e6767900-7307-11e9-9ca8-6fb09ed04c05.png)

**Comment by shankar2105** [comment]
Closing this issue as this is similar to #357

**Comment by safesurfer** [comment]
Since it is similar to #357 and referenced to it, moving it to done.
