### ISSUE TITLE
Safecoin - Text moves to bottom of video at browser XS - MacOS, Safari

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#340]
"Safecoin; The Currency for Security and Privacy" should be above the video player:
![image](https://user-images.githubusercontent.com/44327924/57526358-1f711680-7325-11e9-9727-b9ff84a78bad.png)
At XS (768 pixels and below) the text moves to the bottom of the video:
![image](https://user-images.githubusercontent.com/44327924/57526446-57785980-7325-11e9-8dbc-9c9d95b98bab.png)

**Comment by JimCollinson** [comment]
At `XXS` (768px and below) the text should indeed be below the video.

**Comment by calumcraig** [comment]
Not an issue - moving to done and labelling won't fix.
