### ISSUE TITLE
Safecoin Page: Safecoin image poster should be real `poster` within video element, not a background image.

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#343]

**Comment by calumcraig** [comment]
Testing on `dev` branch: `446dd97 (HEAD -> dev, origin/dev) Thin background videos (#345)`

There is a poster element in the video when the page is loaded or reloaded:

![image](https://user-images.githubusercontent.com/44327924/57761246-0ab1cb80-76f5-11e9-853d-e54c96b1483e.png)

QA verified, moving to done.
