### ISSUE TITLE
How it works - click roadmap link, back button doesn't return to same place

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#349]
Testing on `dev` branch: `3cfec26 (HEAD -> dev, origin/dev) Update background video, video overlay and animated gif (#337)`

1. How it works page
2. Click on "See the Roadmap" link:
![image](https://user-images.githubusercontent.com/44327924/57606751-7b27e380-7561-11e9-9b97-150627945a8f.png)
3. Navigate to roadmap page.
4. Click back on browser.

**Expected:**
User is returned to same part of the page they came from.
**Actual:**
User is taken to the top of the How it Works page:
![image](https://user-images.githubusercontent.com/44327924/57606848-af030900-7561-11e9-97ec-4046bb1accd4.png)

**Comment by shankar2105** [comment]
Closing this issue as this is similar to #357

**Comment by safesurfer** [comment]
Since it is similar to #357 and referenced to it, moving it to done.
