### ISSUE TITLE
Homepage: very last BG video on the page doesn't quite get the full height it needs at small viewports.

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#352]
One tiny thing... the very last BG video on the page doesn't quite get the full height it needs at small viewports.

<img width="378" alt="Screenshot 2019-05-13 12 34 02" src="https://user-images.githubusercontent.com/13061030/57618652-eed6ea00-757b-11e9-8e1a-b0b8cab0be0e.png">

_Originally posted by @JimCollinson in https://github.com/maidsafe/safenetwork.tech/pull/351#issuecomment-491787239_

**Comment by S-Coyle** [comment]
PR already approved by Jim, tested in Chrome, FF & Safari and all seems fine. QA verified
