### ISSUE TITLE
Website v1.1 MS Edge issues

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#355]
**How it Works:**
How it works is not displaying the elements at the top of the screen - it seems the background is covering the intro paragraph and links:
![image](https://user-images.githubusercontent.com/44327924/57625835-90fece00-758c-11e9-936c-3ab81dad5e16.png)

The above was found using `Microsoft Edge 42.17134.1.0` on Windows 10.

**Comment by safesurfer** [comment]
**Homepage:**
the video covers the content.
![image (7)](https://user-images.githubusercontent.com/27578024/57687329-e0123500-7658-11e9-960e-1e26b8ccdd95.png)

it should be like the following
![image (6)](https://user-images.githubusercontent.com/27578024/57687340-ea343380-7658-11e9-8bf7-365b1102c24b.png)

**Comment by safesurfer** [comment]
**Safecoin:**
`More FAQs` button is missing in `Safecoin` page, when the page width is greater than 1300 pixels
![image (5)](https://user-images.githubusercontent.com/27578024/57687431-0a63f280-7659-11e9-8205-542eb15760e5.png)

**Comment by calumcraig** [comment]
At medium browser size (1300 - 1600):
![image](https://user-images.githubusercontent.com/44327924/57782018-495e7a80-7723-11e9-8a6f-1f5bdda67148.png)

**Comment by safesurfer** [comment]
QA verified
