### ISSUE TITLE
Hover and Pressed state of Underline links are not as in figma

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safenetwork.tech#362]
Pressed state of the links available in the `Home Page` are not as in Figma's `Intro Link`. The pressed state doesn't show yellow line.

![image](https://user-images.githubusercontent.com/27578024/57695662-78fe7b80-766c-11e9-9562-d711fb382048.png)

In `Home Page`, the pressed state of `Read more about the design`, which is `Underline Link / Bright on Yellow`, doesn't turn in to White. One more on `How it works` page also.

![image](https://user-images.githubusercontent.com/27578024/57695789-d09ce700-766c-11e9-83c0-3261191e07c8.png)

In `Safecoin` page, the Hover and Pressed state of the FAQ links (`FAQ / Collapsed`) are having issue. Same on `FAQ Page` also.

![image](https://user-images.githubusercontent.com/27578024/57696014-66387680-766d-11e9-916e-71fd51582c9d.png)

* Note: Kindly check for any other similar issues with link.

**Comment by S-Coyle** [comment]
This very first issue of the 3 above - home page with light grey background - has been resolved, however it seems the other 2 issues are not resolved to match what has been specified on Figma (see components page).
Moving back to In Development

**Comment by calumcraig** [comment]
Testing on `dev` branch: `b186625 (HEAD -> dev, origin/dev) chore/conflicts: fix merge conflicts`

The above two issues have now been resolved - verified hover and press states are correct for `Read more about the design` and `FAQs` - both on `Safecoin` page and `FAQs`.

Closing and moving to done.
