### ISSUE TITLE
Cookies policy - add "No cookies" policy content

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#365]
The content for the new cookie policy page has what seems like generic content which is not applicable to `safenetwork.tech`:

**Eg:**
![image](https://user-images.githubusercontent.com/44327924/57703967-fc15d680-7658-11e9-9b66-519c33a36513.png)
![image](https://user-images.githubusercontent.com/44327924/57704042-1485f100-7659-11e9-8a41-989d1af006dc.png)

This sentence at the start of the policy page is particularly inapplicable:
"Your acceptance of Our Cookie Policy is deemed to occur when you press the accept button on Our Cookie banner pop up. If you do not agree to Our Cookie Policy, please stop using Our Site immediately."

This contradicts our current `safenetwork.tech/cookies` page which clearly states that (with the exception of those who participate in the Alpha 2 trials) we have a *no cookies* policy:
![image](https://user-images.githubusercontent.com/44327924/57704185-557e0580-7659-11e9-8c71-c7ebd6e7ddab.png)
For reference, `maidsafe.net/cookies` currently displays no cookies as well:
![image](https://user-images.githubusercontent.com/44327924/57704415-bf96aa80-7659-11e9-9bcc-6108e4a78b92.png)

**Expected:**
New cookies policy page to state no cookies policy.

**Comment by S-Coyle** [comment]
Reviewed & QA'd 👍
