### ISSUE TITLE
Cookie Policy - no yellow bar in header

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#366]
Testing latest `dev` branch commit: `446dd97 (HEAD -> dev, origin/dev) Thin background videos (#345)`

**Expected** (from Figma):
![image](https://user-images.githubusercontent.com/44327924/57707437-8e20dd80-765f-11e9-8edc-89a71f24149b.png)
**Actual:**
![image](https://user-images.githubusercontent.com/44327924/57707509-aabd1580-765f-11e9-87f5-392cf53b4d96.png)

**Comment by S-Coyle** [comment]
QA verified on Chrome, FF & Safari
