### ISSUE TITLE
Homepage - typo

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#370]
**Expected:**
The SAFE Network turns the current data ownership model on _its_ head.

**Actual:**
The SAFE Network turns the current data ownership model on _it’s_ head.
![image](https://user-images.githubusercontent.com/44327924/57763729-eb696d00-76f9-11e9-8f02-f48982069f1f.png)

**Comment by safesurfer** [comment]
QA verified
