### ISSUE TITLE
Homepage - missing full stop

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#372]
On the homepage the quote from David should be properly punctuated as it is a complete sentence - so it needs a full stop at the end.

**Expected:**
"Fixing the Internet isn't optional, and now there's a solution we can all be part of."
**Actual:**
"Fixing the Internet isn't optional, and now there's a solution we can all be part of"
![image](https://user-images.githubusercontent.com/44327924/57765372-3933a480-76fd-11e9-92a0-e8ea0c2ec116.png)

**Comment by safesurfer** [comment]
QA verified
