### ISSUE TITLE
Homepage - extra word added to sentence

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#373]
Testing `dev` branch: `446dd97 (HEAD -> dev, origin/dev) Thin background videos (#345)`

There is an extra "of" in the Total Privacy, Absolute Security section. 

**Expected:**
"That’s why the SAFE Network encrypts all data by default, ..."
**Actual:**
"That’s why the SAFE Network encrypts _of_ all data by default, ..."
![image](https://user-images.githubusercontent.com/44327924/57767392-24f1a680-7701-11e9-8ba6-3a800a99535e.png)

**Comment by safesurfer** [comment]
QA verified
