### ISSUE TITLE
Homepage - "necessary" spelled incorrectly

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#375]
Testing `dev` branch: `446dd97 (HEAD -> dev, origin/dev) Thin background videos (#345)`

Homepage:

**Expected:**
"necessary"
**Actual:**
"nessecary"
![image](https://user-images.githubusercontent.com/44327924/57767822-2ff90680-7702-11e9-8af8-4d924a54eb6e.png)

**Comment by safesurfer** [comment]
QA verified
