### ISSUE TITLE
Homepage - missing "a"

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#376]
Testing `dev` branch: `446dd97 (HEAD -> dev, origin/dev) Thin background videos (#345)`

There is a missing "a" in a sentence under "Pay once, store forever".

**Expected:**
"You’ll pay _a_ minimal, one-time, upload charge but you’ll get permanent secure backups with no more monthly fees."
**Actual:**
"You’ll pay minimal, one-time, upload charge but you’ll get permanent secure backups with no more monthly fees."
![image](https://user-images.githubusercontent.com/44327924/57768251-21f7b580-7703-11e9-8765-df20190b74c1.png)

**Comment by safesurfer** [comment]
QA verified
