### ISSUE TITLE
Homepage - missing "s"

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#377]
Testing `dev` branch: `446dd97 (HEAD -> dev, origin/dev) Thin background videos (#345)`

**Expected:**
"Being in complete control _means_ you can quickly and easily move your data between apps and services. Mix and match to meet your needs, and leave no data behind."
**Actual:**
"Being in complete control mean you can quickly and easily move your data between apps and services. Mix and match to meet your needs, and leave no data behind."
![image](https://user-images.githubusercontent.com/44327924/57768495-a9ddbf80-7703-11e9-8184-aef662bd4c75.png)

**Comment by safesurfer** [comment]
QA verified
