### ISSUE TITLE
Homepage - "guarantees" spelled incorrectly

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#378]
Testing `dev` branch: `446dd97 (HEAD -> dev, origin/dev) Thin background videos (#345)`

**Expected:**
"guarantees"
**Actual:**
"guarentees"
![image](https://user-images.githubusercontent.com/44327924/57769071-e8c04500-7704-11e9-9dc6-18db409f70a4.png)

**Comment by safesurfer** [comment]
QA verified
