### ISSUE TITLE
Homepage - MS Edge issue

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#381]
Testing `dev` branch: `446dd97 (HEAD -> dev, origin/dev) Thin background videos (#345)`

On MS Edge there is an issue at M size (1300 - 1600):

![image](https://user-images.githubusercontent.com/44327924/57782204-ace8a800-7723-11e9-86c2-c72e5403c5d9.png)

**Comment by safesurfer** [comment]
QA verified.

![image](https://user-images.githubusercontent.com/27578024/57846622-41b9d700-77f2-11e9-9edb-4b92ff1c8cba.png)
