### ISSUE TITLE
Homepage - MS Edge issue at XXXS size

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safenetwork.tech#383]
Testing `dev` branch: `446dd97 (HEAD -> dev, origin/dev) Thin background videos (#345)`

At XXXS size (less than 500 wide) on MS Edge the background videos overlap the other boxes around the "One Password. For real this time." box:
![image](https://user-images.githubusercontent.com/44327924/57784698-42863680-7728-11e9-8b73-ad1eb31b27e5.png)

**Comment by safesurfer** [comment]
QA verified and moving it to Done

![image](https://user-images.githubusercontent.com/27578024/57846740-7ded3780-77f2-11e9-8b4d-9cc9a69a51c2.png)
