### ISSUE TITLE
Roadmap: Broken accordion layout at ≥`S`

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#387]

**Comment by shankar2105** [comment]
Closing as this issue no longer exist

**Comment by calumcraig** [comment]
Testing on `dev` branch: `b186625 (HEAD -> dev, origin/dev) chore/conflicts: fix merge conflicts`

Verified that all accordion sections are working correctly at S size.

Moving this issue to done.
