### ISSUE TITLE
Roadmap: Add App images to roadmap page (large, medium and small)

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#398]
Images after this messge in the website slack channel: https://maidsafe.slack.com/archives/C29U5J68G/p1557758945179300

**Comment by calumcraig** [comment]
Testing on `dev` branch: `b186625 (HEAD -> dev, origin/dev) chore/conflicts: fix merge conflicts`

Large images:
![image](https://user-images.githubusercontent.com/44327924/57927169-3f648500-78a5-11e9-8cb1-17bb5d0005d0.png)

Small:
![image](https://user-images.githubusercontent.com/44327924/57927248-5f944400-78a5-11e9-90bc-a4587980ef1e.png)

Very small:
![image](https://user-images.githubusercontent.com/44327924/57927402-cca7d980-78a5-11e9-9247-92c39a0efe40.png)

**Comment by calumcraig** [comment]
QA verified - closing issue and moving to done.
