### ISSUE TITLE
PR#70 FAQ: Vault rewording changes

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safenetwork.tech#4]
Community feedback from https://safenetforum.org/t/the-new-website-revealed/24593/34?u=nadia

" Collectively, Vaults manage the storage of all data on the Network by managing the movement of chunks of encrypted user data [that] are stored across the Network."

Edit to add: Also in What is a Vault? section: “Disjoint Section” is used but not defined anywhere I can see, at least not near this. The term “section” is used and should do fine here as well. “Disjoint” undefined adds potential confusion.

**Comment by david-maidsafe** [comment]
DWG: Fixed and waiting to commit with other corrections.

**Comment by pravarseth** [comment]
QA Verified
