### ISSUE TITLE
Roadmap: Need the ability to take the CTA out of the `Latest Update` bit at the top of the roadmap.

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#401]

**Comment by calumcraig** [comment]
There is currently no CTA link in the `Latest Update` section at the top of the page:

![image](https://user-images.githubusercontent.com/44327924/57931046-75a70200-78af-11e9-8f79-61aefc6eee36.png)

Closing and moving to done.
