### ISSUE TITLE
Roadmap: None of the CTA buttons on the roadmap page work

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#403]

**Comment by calumcraig** [comment]
Testing on `dev` branch: `b186625 (HEAD -> dev, origin/dev) chore/conflicts: fix merge conflicts`

Tested all links such as:

![image](https://user-images.githubusercontent.com/44327924/57930422-db928a00-78ad-11e9-9dcc-af5c6803eb64.png)

All are opening the appropriate links in a new browser tab.

**Comment by calumcraig** [comment]
QA verified - closing issue and moving to done.
