### ISSUE TITLE
Roadmap: Need ability to anchor down to individual sections and feature items (need to add IDs)

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#404]

**Comment by calumcraig** [comment]
Testing on `dev`: `b186625 (HEAD -> dev, origin/dev) chore/conflicts: fix merge conflicts`

Can be seen that all section items (the accordion components) have anchors, eg `/#vault-user-interface`

This is seen in live too.

Closing this issue and moving to done.
