### ISSUE TITLE
How It Works: Missing (psuedo) Poster BG Image for the birds video

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#405]
Image here vvvvv

![Birds-Poster-x1280-Q20](https://user-images.githubusercontent.com/13061030/57866875-fc98a380-77f7-11e9-9c58-7ea073bcc2b2.jpg)

**Comment by calumcraig** [comment]
Testing on `dev`: `b186625 (HEAD -> dev, origin/dev) chore/conflicts: fix merge conflicts`

Removing the `<video>` element from the page source results in the background poster element being exposed:

![image](https://user-images.githubusercontent.com/44327924/58011293-da4da100-7ae9-11e9-90e4-27bd2c38a6f0.png)

**Comment by calumcraig** [comment]
QA verified, closing and moving to done.
