### ISSUE TITLE
Please update secure message relay and data types to be at RFC stage

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/safenetwork.tech#408]
Now that these RFC's are released to the community, their website status needs to be updated please

**Comment by JimCollinson** [comment]
@nadiaburborough @dugcampbell We have two RFCs for data types, so I'd recommend we split it out into two features on the roadmap: `Unpublished ImmutableData` and `Published and Unpublished DataType`.

Anyone wanna help me out with a short and long description?

**Comment by JimCollinson** [comment]
Do we also need the earlier `Mutable` and `ImmutableData` features listed in Alpha 2, as these build upon them?

**Comment by JimCollinson** [comment]
Also, should `Secure Message Relay` be titled `Secure Message Delivery`?

**Comment by nadiaburborough** [comment]
> recommend we split it out into two features on the roadmap
👍 

> need the earlier Mutable and ImmutableData
IMO as these build on and essentially superceed these, I'd leave them off. There are a lot of RFC's that are aren't explicitly mentioned in the roadmap also. But they are visible through the current RFC (referenced) and also open in the RFC repo. 

> help me out with a short and long description

here's the text from the RFC's .... (i've paraphrased to reduce the long description)
**Published and Unpublished DataType**: allow the network to store Published and Unpublished data via AppendOnlyData or MutableData types
Long description: Published data refers to content that is published (made available) for everyone such as websites, blogs, or research papers. For such public content, it becomes important to retain a history of changes. History must not be allowed to be tampered with and the published data must remain forever. Unpublished data is data that is not desired to be made public such as personal data or organisations' data stored on the network. 

**Unpublished ImmutableData**: enhance ImmutableData to make it an unpublished or published, with the difference that unpublished can be deleted.

long description: There are many a times when a user will require to create Immutable Data to store private content. As long as this content is not published (made available for others) this will be deleteable by the data owner only.

**Comment by calumcraig** [comment]
Testing on `dev`: `b186625 (HEAD -> dev, origin/dev) chore/conflicts: fix merge conflicts`

Can see these sections have been updated to indeed reflect "RFC":

![image](https://user-images.githubusercontent.com/44327924/58017103-484c9500-7af7-11e9-9e0d-783189daebb5.png)

![image](https://user-images.githubusercontent.com/44327924/58017289-b98c4800-7af7-11e9-9bfd-d079eba3ed6e.png)

QA verified - moving to done.
