### ISSUE TITLE
Background video taking focus on mobile

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/safenetwork.tech#411]
## STR:
1. On mobile (iOS) navigate to How it Works page 
2. Page loads initially, then the video (which was playing as part of the background) takes full focus of the screen (rather than remaining in the background)
3. Tap screen, tap X to return to website

**Comment by calumcraig** [comment]
Currently unable to replicate this on Android.

**Comment by calumcraig** [comment]
This is reported to be resolved on the live website so closing the issue and moving to done.
