### ISSUE TITLE
Fonts taking a *long* time to load giving a FOUC

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#427]
We had a similar issue on the previous version of the site IIRC, which was fixed here:

https://github.com/shankar2105/safenetwork.tech/commit/949a7535206fbb957066219e26e4721323ede503

Don't know if it is the same issue, requiring the same solution?

**Comment by calumcraig** [comment]
Tested loading times for the homepage. Each time launched `safenetwork.tech` in a new incognito / private window (so no cache):


Mobile: | Android | Desktop: | Chromium | Firefox:
-- | -- | -- | -- | --
  | 39 |   | 20.9 | 34.6
  | 49.4 |   | 23.5 | 33.3
  | 27.9 |   | 26.3 | 29
  | 35.3 |   | 21.4 | 35
  | 57.1 |   | 20.9 | 40.6
Average: | 41.74 |   | 22.6 | 34.5

**Comment by shankar2105** [comment]
Closing this issue. Fixed in PR #433

**Comment by calumcraig** [comment]
Testing against Netlify preview: https://deploy-preview-433--keen-stonebraker-bb1a10.netlify.com/

Loading time has significantly improved - the site now loads in a couple of seconds, both on desktop and mobile.

Moving to done.
