### ISSUE TITLE
Suggested wording change on SafeCoin page

### ISSUE THREAD

**Issue by david-maidsafe** [maidsafe/safenetwork.tech#43]
Community feedback from https://safenetforum.org/t/the-new-website-revealed/24593/42?u=nadia
> “Share resource, get paid” … resource s/b plural “resources”. They are sharing their resources.

**Comment by david-maidsafe** [comment]
https://github.com/maidsafe/safenetwork_website/issues/263

**Comment by S-Coyle** [comment]
English(UK) vs English (US) here - closing as we follow UK
