### ISSUE TITLE
safecoin RFC is published. Please update the following icons on the roadmap page:

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/safenetwork.tech#436]
https://safenetwork.tech/roadmap/#test-safecoin-&-wallet

https://safenetwork.tech/roadmap/#farming

https://safenetwork.tech/roadmap/#test-safecoin-wallet

**Comment by JimCollinson** [comment]
Will need links to the RFCs in there too presumably

**Comment by nadiaburborough** [comment]
RFC link: https://github.com/maidsafe/rfcs/blob/master/text/0057-safecoin-revised/0057-safecoin-revised.md

Forum discussion link: https://safenetforum.org/t/rfc-57-safecoin-revised/28660

**Comment by calumcraig** [comment]
Can confirm that all the icons have been updated:
![image](https://user-images.githubusercontent.com/44327924/58251924-daa1a280-7d5c-11e9-8e61-139587ef0967.png)
![image](https://user-images.githubusercontent.com/44327924/58251936-de352980-7d5c-11e9-8c74-abc1898fcef4.png)
![image](https://user-images.githubusercontent.com/44327924/58251944-e1301a00-7d5c-11e9-8e4b-8dd377c81961.png)
All links are functioning correctly.
- `Join the discussion` opens the corresponding forum page in the same tab.
- `Read the RFC` opens the RFC GitHub page in a new tab.
