### ISSUE TITLE
Roadmap: Change status of Safe Cli project to 'development' from 'concept'

### ISSUE THREAD

**Issue by vinitha-vasanthkumar** [maidsafe/safenetwork.tech#451]
On the roadmap page the milestone status of Safe Cli project is displayed as 'concept' change it to 'development'.

![image](https://user-images.githubusercontent.com/44664836/59505768-03343c80-8ec4-11e9-8ee0-7ba2b64e32af.png)

**Comment by krishnaIndia** [comment]
This [PR](https://github.com/maidsafe/safenetwork.tech/pull/452) should be resolving this issue once it is merged
