### ISSUE TITLE
Update the Apps section for Safe Browser version release to V.0.14.0

### ISSUE THREAD

**Issue by vinitha-vasanthkumar** [maidsafe/safenetwork.tech#455]
Update the Apps section for Safe Browser version release to V.0.14.0 on 26th Jun 2019
![image](https://user-images.githubusercontent.com/44664836/60079526-bb2ada80-974b-11e9-8efd-cc4df42a24c4.png)

**Comment by shankar2105** [comment]
Closing this issue as it got resolved in #458
