### ISSUE TITLE
Suggested wording addition ("Founder") for front page

### ISSUE THREAD

**Issue by david-maidsafe** [maidsafe/safenetwork.tech#55]
Community feedback from https://safenetforum.org/t/the-new-website-revealed/24593/28?u=nadia

> Put “Founder” after David Irvine's name on the quote frontpage.

**Comment by nadiaburborough** [comment]
Resolved

![Screen Shot 2019-06-24 at 10 47 47 AM](https://user-images.githubusercontent.com/35568923/60009292-89434680-966d-11e9-8b18-c591f152e883.png)
