### ISSUE TITLE
Colour issue with menu bar when scrolling

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safenetwork.tech#61]
When scrolling, menu bar changes colour from dark blue to light grey, and text changes white to black, but the text change and menu bar colour change aren't synchronised to be at the same time.
![scrollissue](https://user-images.githubusercontent.com/37243695/42514902-63a45cc6-8452-11e8-93d3-eec7f0e9011d.gif)

**Comment by nadiaburborough** [comment]
Website has since been redesigned and this is no longer an issue
