### ISSUE TITLE
Suggestion for Timeline link

### ISSUE THREAD

**Issue by david-maidsafe** [maidsafe/safenetwork.tech#62]
Community feedback from TylerAbeoJordan
https://safenetforum.org/t/the-new-website-revealed/24593/4?u=nadia

"the ‘timeline’ link only seems to appear at the top of the page, while other links are repeated in multiple places … sort of gets lost maybe"

**Comment by david-maidsafe** [comment]
https://github.com/maidsafe/safenetwork_website/issues/248

**Comment by nadiaburborough** [comment]
Timeline page replaced with Roadmap page. Link is always available from global footer, or hamburger at top right of page
