### ISSUE TITLE
Accordion transition on FAQs and Footer is ScaleY, would prefer showing through overflow-y hidden/shown instead

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safenetwork.tech#65]

**Comment by S-Coyle** [comment]
Comment from @JimCollinson:
Also: currently does not animate closed

**Comment by S-Coyle** [comment]
Comment by @shankar2105:
@JimCollinson When opening one item closing others doesn't seems to be normal accordion behaviour with reference to some of the examples. So I've changed in such a way opened item stay opened when opening a new one.

Also not sure how overflow-y gonna help us in animation. Could you please explain a bit more.

**Comment by calumcraig** [comment]
Removing from project as has been completed and closed - no longer relevant (feature replaced in the new design).
