### ISSUE TITLE
PR#70 FAQ: "Where can I store MaidSafeCoin" - text duplicated

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safenetwork.tech#7]
The following paragraph in the FAQ section under “Where Can I Store MaidSafeCoin?” is duplicated in the very next paragraph:

“Although they may not be visible within all wallet software, your MaidSafeCoin will be OK there as long as your machine and private key for that address are secure. You will be able to view them using Omnichest.info explorer by inserting that Bitcoin address into the search bar. However, you can also set up an Omniwallet account (a third party web wallet) which will enable you to view MaidSafeCoin within the wallet and to be able to transfer them to another address, or offline Bitcoin wallet.”

**Comment by pravarseth** [comment]
QA Verified
