### ISSUE TITLE
'SAFE Network' branding - don't use all CAPS

### ISSUE THREAD

**Issue by david-maidsafe** [maidsafe/safenetwork.tech#71]
> :bookmark: Personally my main concession to that would be a little more SAFE Network branding, perhaps with ‘Network’ not in caps to bring out the SAFE. Perhaps just a little bigger on the landing page, compared to the subtitle.

:pushpin: https://safenetforum.org/t/the-new-website-revealed/24593/59

**Comment by Karamu76** [comment]
Closing issue as it will be fixed according to the above triage related comments. Also archiving to remove from maintenance board.
