### ISSUE TITLE
Safecoin page: highlight facts/key points more

### ISSUE THREAD

**Issue by david-maidsafe** [maidsafe/safenetwork.tech#74]
> 🔖 The safecoin page:
Personally I would list the safecoin facts(xxx+ TPS, 100% privat, ZERO transaction costs, instant!, etc.) as real selling points. For example big red characters, they must scream. Or put them kind of random on the page, fancifully. Maybe even compare the facts with some blockchain coins.
Now it looks so humble, you just read it without realizing it is the best coin out there.

📌https://safenetforum.org/t/the-new-website-revealed/24593/61

**Comment by Karamu76** [comment]
Closing issue as it will not be fixed according to the above triage related comments. Also archiving to remove from maintenance board.
