### ISSUE TITLE
Homepage: Add period to 'Always free to access' paragraph.

### ISSUE THREAD

**Issue by david-maidsafe** [maidsafe/safenetwork.tech#75]
> 🔖 The “Always Free to Access” paragraph doesn’t end with a period like every other side-note.

📌 https://safenetforum.org/t/the-new-website-revealed/24593/76

**Comment by calumcraig** [comment]
Can confirm this has been fixed at some point:

![image](https://user-images.githubusercontent.com/44327924/55628443-a07a4280-57a8-11e9-8f45-f552eda9ece3.png)

Closing as done.

**Comment by calumcraig** [comment]
Removed from Release project.

**Comment by calumcraig** [comment]
Removing from project as has been completed and closed.
