### ISSUE TITLE
FAQ page font is too big on desktop display

### ISSUE THREAD

**Issue by david-maidsafe** [maidsafe/safenetwork.tech#76]
> 🔖 The font on the Q&A page is way too big on my desktop display. Makes it hard to read without regular scrolling.

📌 https://safenetforum.org/t/the-new-website-revealed/24593/98

**Comment by david-maidsafe** [comment]
I _think_ this is simply 'by design' as I do think the font is towards the larger side for standard text but not overly so (IMO).  Logging for completeness.

**Comment by shankar2105** [comment]
Current implementation has `2.1875vw` as the font-size for FAQ title and answers, which we defined in proportion to the breakpoint. We need @JimCollinson 's suggestion to alter this for a better view at <=1399px.
