### ISSUE TITLE
Terminology: should “internet” be replaced with “World Wide Web”

### ISSUE THREAD

**Issue by david-maidsafe** [maidsafe/safenetwork.tech#77]
Question regarding **Contribute and be rewarded** section:
> 🔖 10. Should “internet” be replaced with “World Wide Web” it’s the world wide web model that is supported by ad revenue. I pay a service provider for “internet” access, I don’t pay anyone for WWW access.

📌 https://safenetforum.org/t/the-new-website-revealed/24593/102

**Comment by Karamu76** [comment]
Closing issue as it will not be fixed according to the above triage related comments. Also archiving to remove from maintenance board.
