### ISSUE TITLE
Flash of Unstyled Fonts on Inital Load

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/safenetwork.tech#88]
Still getting the flash of unstyled fonts on (every) initial load. Don't get it when moving to subsequent pages in the same session.

Be great if we could find a way for avoid this, or at best a more graceful load on fonts.

**Comment by S-Coyle** [comment]
Tested on Chrome, Firefox and Safari, with multiple pages from the site (clearing cache & hard reload) - no sign of initial flash of unstyled fonts
