### ISSUE TITLE
'Download Browser' on 'How it works' page automatically downloads linux version for safe_browser. I'm on a Mac - I want the os version. Should it take me to the release page first?

### ISSUE THREAD

**Issue by SarahPentland** [maidsafe/safenetwork.tech#94]

**Comment by joshuef** [comment]
I think just pointing to releases is also quite future proof too. Less updates to be done when we update the browser.

**Comment by Karamu76** [comment]
Closing issue as it will not be fixed according to the above triage related comments. 

Also archiving to remove from maintenance board.
